---
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    hostname: homer
    ports:
      - 8092:8080
    environment:
      - INIT_ASSETS=0
      - PUID=${PUID}
      - PGID=${PGID}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./config/config.yml:/www/assets/config.yml
      - ./data/css:/www/assets/css
      - ./data/icons:/www/assets/icons
      - ./data/backgrounds:/www/assets/backgrounds
    restart: unless-stopped