---
title: "Dashboard"
subtitle: "Home Lab"
documentTitle: "Home Lab Dashboard"
logo: "/assets/icons/white_gears.png"
header: true
footer: false
columns: "3"

defaults:
  layout: columns
  colorTheme: auto

stylesheet:
  - "/assets/css/custom.css"

theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#5A5A5A"
    text-header: "#FFFFFF"
    text-title: "#5A5A5A"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "/assets/backgrounds/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "/assets/backgrounds/bg.png"

links:
  - name: "GitHub"
    icon: ""
    url: "https://github.com"
    target: "_blank"
  - name: "PyPi"
    icon: ""
    url: "https://pypi.org/"
    target: "_blank"
  - name: "Docker Hub"
    icon: ""
    url: "https://hub.docker.com"
    target: "_blank"

services:
  - name: "Network"
    icon: ""
    items:
      - name: "Unifi Controller"
        logo: "/assets/icons/unifi.png"
        subtitle: "Unifi Controller"
        url: "https://unifi.${DOMAIN}.com"
        target: "_blank"
      - name: "Arris Modem"
        logo: "/assets/icons/arris.png"
        subtitle: "Arris SB6183 Modem"
        url: "https://modem.${DOMAIN}.com"
        target: "_blank"
  - name: "Home Control"
    icon: ""
    items:
      - name: "Hubitat"
        logo: "/assets/icons/hubitat.png"
        subtitle: "Hubitat Hub"
        url: "https://hubitat.${DOMAIN}.com"
        target: "_blank"
      - name: "Synology DS720+"
        logo: "/assets/icons/synology.png"
        subtitle: "Synolgoy DiskStation NAS"
        url: "https://synology.${DOMAIN}.com"
        target: "_blank"
      - name: "Denon AVR"
        logo: "/assets/icons/denon.png"
        subtitle: "Denon AVR X3600H"
        url: "https://denon.${DOMAIN}.com"
        target: "_blank"
  - name: "Docker Containers"
    icon: ""
    items:
      - name: "Portainer"
        logo: "/assets/icons/portainer.png"
        subtitle: "Docker Container Management"
        url: "https://portainer.${DOMAIN}.com"
        target: "_blank"
      - name: "Nginx Proxy Manager"
        logo: "/assets/icons/nginxproxymanager.png"
        subtitle: "Nginx Proxy Management"
        url: "https://npm.${DOMAIN}.com"
        target: "_blank"
      - name: "Pihole"
        logo: "/assets/icons/pihole.png"
        subtitle: "Ad Blocker"
        url: "https://pihole.${DOMAIN}.com"
        target: "_blank"
      - name: "Prometheus"
        logo: "/assets/icons/prometheus.png"
        subtitle: "Prometheus Collector"
        url: "https://${SERVER}:9090"
        target: "_blank"
      - name: "Prometheus Alertmanager"
        logo: "/assets/icons/prometheus.png"
        subtitle: "Prometheus Alerts"
        url: "https://${SERVER}:9093"
        target: "_blank"
      - name: "Prometheus BlackBox"
        logo: "/assets/icons/prometheus.png"
        subtitle: "Prometheus Exporter"
        url: "https://${SERVER}:9115"
        target: "_blank"
      - name: "Grafana"
        logo: "/assets/icons/grafana.png"
        subtitle: "Grafana Dashboard"
        url: "https://${SERVER}:3000/"
        target: "_blank"
  - name: "External Utilities"
    icon: ""
    items:
      - name: "Public IP"
        logo: ""
        subtitle: "Public IP Address"
        url: "https://www.whatismyip.com"
        target: "_blank"
      - name: "Speed Test"
        logo: ""
        subtitle: "WAN Speed Test"
        url: "https://speed.cloudflare.com"
        target: "_blank"
      - name: "Whois Lookup"
        logo: ""
        subtitle: "Internet Resource Lookup"
        url: "https://lookup.icann.org"
        target: "_blank"
